"use client";

export default function Reports() {
  return (
    <main className="min-h-screen bg-slate-950 text-white flex">

      {/* Sidebar */}
      <aside className="w-64 bg-slate-900 border-r border-slate-800 p-6 hidden md:block">

        <h1 className="text-3xl font-bold text-blue-500 mb-10">
          LOOP
        </h1>

        <nav className="space-y-3">

          <div className="px-4 py-3 text-slate-400">
            Dashboard
          </div>

          

          <div className="px-4 py-3 text-slate-400">
            Feedback Inbox
          </div>

          <div className="px-4 py-3 text-slate-400">
            Themes & Trends
          </div>

          <div className="px-4 py-3 text-slate-400">
            Ask LOOP
          </div>

          <div className="bg-blue-600 rounded-lg px-4 py-3">
            Reports
          </div>

        </nav>

      </aside>

      {/* Main */}
      <section className="flex-1 p-6 md:p-10">

        <div className="max-w-6xl mx-auto">

          {/* Header */}
          <div className="flex flex-col md:flex-row justify-between gap-5 mb-8">

            <div>
              <h2 className="text-3xl font-bold">
                Voice of Customer Report
              </h2>

              <p className="text-slate-400 mt-2">
                A summary of what your customers are saying.
              </p>
            </div>

            <button className="bg-blue-600 hover:bg-blue-700 px-6 py-3 rounded-lg font-semibold">
              ↓ Download Report
            </button>

          </div>

          {/* Report Info */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 mb-6">

            <div className="flex flex-col md:flex-row justify-between gap-4">

              <div>
                <p className="text-sm text-slate-500">
                  REPORT PERIOD
                </p>

                <p className="text-lg font-semibold mt-1">
                  August 1 – August 26, 2026
                </p>
              </div>

              <div>
                <p className="text-sm text-slate-500">
                  FEEDBACK ANALYZED
                </p>

                <p className="text-lg font-semibold mt-1">
                  1,248
                </p>
              </div>

              <div>
                <p className="text-sm text-slate-500">
                  GENERATED BY
                </p>

                <p className="text-lg font-semibold mt-1">
                  LOOP AI
                </p>
              </div>

            </div>

          </div>

          {/* Sentiment */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-6">

            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">

              <p className="text-slate-400">
                Positive
              </p>

              <p className="text-4xl font-bold text-green-400 mt-2">
                68%
              </p>

              <p className="text-sm text-green-400 mt-2">
                ↑ 8.2% from previous period
              </p>

            </div>

            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">

              <p className="text-slate-400">
                Neutral
              </p>

              <p className="text-4xl font-bold text-yellow-400 mt-2">
                18%
              </p>

              <p className="text-sm text-slate-400 mt-2">
                Stable
              </p>

            </div>

            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">

              <p className="text-slate-400">
                Negative
              </p>

              <p className="text-4xl font-bold text-red-400 mt-2">
                14%
              </p>

              <p className="text-sm text-green-400 mt-2">
                ↓ 3.4% from previous period
              </p>

            </div>

          </div>

          {/* Top Themes */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 mb-6">

            <h3 className="text-xl font-semibold mb-6">
              🏷️ Top Customer Themes
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-5">

              <div className="bg-slate-800 rounded-xl p-5">
                <p className="text-sm text-slate-400">
                  #1 Theme
                </p>

                <h4 className="text-xl font-semibold mt-2">
                  User Experience
                </h4>

                <p className="text-blue-400 mt-2">
                  324 feedback items
                </p>
              </div>

              <div className="bg-slate-800 rounded-xl p-5">
                <p className="text-sm text-slate-400">
                  #2 Theme
                </p>

                <h4 className="text-xl font-semibold mt-2">
                  Customer Support
                </h4>

                <p className="text-blue-400 mt-2">
                  267 feedback items
                </p>
              </div>

              <div className="bg-slate-800 rounded-xl p-5">
                <p className="text-sm text-slate-400">
                  #3 Theme
                </p>

                <h4 className="text-xl font-semibold mt-2">
                  Mobile App
                </h4>

                <p className="text-blue-400 mt-2">
                  198 feedback items
                </p>
              </div>

            </div>

          </div>

          {/* Trending Issues */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 mb-6">

            <h3 className="text-xl font-semibold mb-6">
              🔥 Trending Issues
            </h3>

            <div className="space-y-4">

              <div className="bg-slate-800 rounded-xl p-5">

                <div className="flex justify-between gap-4">

                  <div>
                    <h4 className="font-semibold">
                      Mobile Performance
                    </h4>

                    <p className="text-sm text-slate-400 mt-2">
                      Customers are reporting slow loading
                      times on mobile devices.
                    </p>
                  </div>

                  <span className="text-red-400 font-semibold">
                    +31%
                  </span>

                </div>

              </div>

              <div className="bg-slate-800 rounded-xl p-5">

                <div className="flex justify-between gap-4">

                  <div>
                    <h4 className="font-semibold">
                      Customer Support
                    </h4>

                    <p className="text-sm text-slate-400 mt-2">
                      Customers want faster responses from
                      the support team.
                    </p>
                  </div>

                  <span className="text-yellow-400 font-semibold">
                    +12%
                  </span>

                </div>

              </div>

            </div>

          </div>

          {/* Customer Quotes */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 mb-6">

            <h3 className="text-xl font-semibold mb-6">
              💬 Customer Voice
            </h3>

            <div className="space-y-4">

              <div className="border-l-4 border-blue-500 pl-5">

                <p className="text-slate-300 italic">
                  "The new dashboard is very easy to use."
                </p>

                <p className="text-sm text-slate-500 mt-2">
                  — Customer feedback #1042
                </p>

              </div>

              <div className="border-l-4 border-red-500 pl-5">

                <p className="text-slate-300 italic">
                  "The application loads very slowly on my
                  mobile phone."
                </p>

                <p className="text-sm text-slate-500 mt-2">
                  — Customer feedback #987
                </p>

              </div>

              <div className="border-l-4 border-yellow-500 pl-5">

                <p className="text-slate-300 italic">
                  "Customer support should respond faster."
                </p>

                <p className="text-sm text-slate-500 mt-2">
                  — Customer feedback #921
                </p>

              </div>

            </div>

          </div>

          {/* AI Recommendations */}
          <div className="bg-blue-950/40 border border-blue-900 rounded-xl p-6">

            <h3 className="text-xl font-semibold text-blue-400">
              🤖 AI Recommended Actions
            </h3>

            <div className="mt-5 space-y-4">

              <div className="flex gap-4">

                <span className="text-blue-400 font-bold">
                  01
                </span>

                <div>
                  <h4 className="font-semibold">
                    Improve mobile performance
                  </h4>

                  <p className="text-sm text-slate-400 mt-1">
                    Prioritize mobile optimization and
                    reduce application loading time.
                  </p>
                </div>

              </div>

              <div className="flex gap-4">

                <span className="text-blue-400 font-bold">
                  02
                </span>

                <div>
                  <h4 className="font-semibold">
                    Improve support response time
                  </h4>

                  <p className="text-sm text-slate-400 mt-1">
                    Review support workflows and reduce
                    customer waiting time.
                  </p>
                </div>

              </div>

              <div className="flex gap-4">

                <span className="text-blue-400 font-bold">
                  03
                </span>

                <div>
                  <h4 className="font-semibold">
                    Prioritize user experience improvements
                  </h4>

                  <p className="text-sm text-slate-400 mt-1">
                    Use customer feedback to improve the
                    most requested product areas.
                  </p>
                </div>

              </div>

            </div>

          </div>

        </div>

      </section>

    </main>
  );
}